import { Resend } from 'resend'
import { NextResponse } from 'next/server'
// import { createClient } from '@/utils/supabase/server'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  console.log('API route hit!')
  try {
    // Check if RESEND_API_KEY is set
    if (!process.env.RESEND_API_KEY) {
      console.error('RESEND_API_KEY is not set in environment variables')
      return NextResponse.json({ error: 'Email service not configured' }, { status: 500 })
    }

    const { title, description } = await request.json()
    console.log('Sending email to: cube2958@gmail.com')

    const { data, error } = await resend.emails.send({
      from: 'Daredevil <onboarding@resend.dev>',
      to: ['cube2958@gmail.com'], // Hardcoded email address
      subject: `[ALERT] ${title}`,
      html: `
        <h2 style="color: #ff0000; font-family: 'Poppins', sans-serif;">${title}</h2>
        <p style="font-family: 'Poppins', sans-serif;">${description}</p>
        <p style="font-style: italic; font-family: 'Poppins', sans-serif;">This alert was generated by Daredevil's real-time monitoring system.</p>
      `
    })

    if (error) {
      console.error('Resend API error:', error)
      return NextResponse.json({ error })
    }
    console.log('Email sent successfully:', data)

    return NextResponse.json({ data })
  } catch (error) {
    console.error('Unexpected error in email API:', error)
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unknown error' })
  }
}
