import { NextResponse } from 'next/server'
import twilio from 'twilio'

export async function POST(request: Request) {
  console.log('WhatsApp API route hit!')
  try {
    // Check if Twilio credentials are set
    if (!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_AUTH_TOKEN) {
      console.error('Twilio credentials are not set in environment variables')
      return NextResponse.json({ error: 'WhatsApp service not configured' }, { status: 500 })
    }

    // Initialize Twilio client
    const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN)
    
    const { title, description } = await request.json()
    const from = process.env.TWILIO_WHATSAPP_FROM
    const to = process.env.TWILIO_WHATSAPP_TO
    
    console.log(`Sending WhatsApp message to: ${to}`)

    // Format the message
    const message = `*[ALERT] ${title}*\n\n${description}\n\nThis alert was generated by Investicore AI's real-time monitoring system.`

    // Send WhatsApp message using Twilio
    const result = await client.messages.create({
      body: message,
      from: `whatsapp:${from}`,
      to: `whatsapp:${to}`
    })

    console.log('WhatsApp message sent successfully:', result.sid)
    return NextResponse.json({ data: { sid: result.sid } })
  } catch (error) {
    console.error('Unexpected error in WhatsApp API:', error)
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unknown error' })
  }
}
