import { NextResponse } from 'next/server'
import twilio from 'twilio'

const MAX_WHATSAPP_BODY_LENGTH = 1500

function normalizeWhatsappAddress(value: string, fieldName: string): string {
  const trimmed = value.trim()
  if (!trimmed) {
    throw new Error(`${fieldName} is empty`)
  }

  if (trimmed.startsWith('whatsapp:')) {
    return trimmed
  }

  // Accept +<country><number> and convert to WhatsApp channel format.
  if (/^\+?\d{8,15}$/.test(trimmed)) {
    const normalized = trimmed.startsWith('+') ? trimmed : `+${trimmed}`
    return `whatsapp:${normalized}`
  }

  throw new Error(`${fieldName} must be a valid phone number (e.g. +14155552671)`)
}

function truncateText(input: string, limit = MAX_WHATSAPP_BODY_LENGTH): string {
  if (input.length <= limit) return input
  return `${input.slice(0, limit - 20)}\n\n[Message truncated]`
}

export async function POST(request: Request) {
  console.log('WhatsApp API route hit!')
  try {
    // Check if Twilio credentials are set
    if (!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_AUTH_TOKEN) {
      console.error('Twilio credentials are not set in environment variables')
      return NextResponse.json({ error: 'WhatsApp service not configured' }, { status: 500 })
    }

    // Initialize Twilio client
    const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN)
    
    const { title, description, fullExplanation, aiMessage } = await request.json()
    const from = process.env.TWILIO_WHATSAPP_FROM
    const to = process.env.TWILIO_WHATSAPP_TO

    if (!from || !to) {
      return NextResponse.json(
        { error: 'TWILIO_WHATSAPP_FROM and TWILIO_WHATSAPP_TO must be configured' },
        { status: 500 }
      )
    }

    const formattedFrom = normalizeWhatsappAddress(from, 'TWILIO_WHATSAPP_FROM')
    const formattedTo = normalizeWhatsappAddress(to, 'TWILIO_WHATSAPP_TO')
    console.log(`Sending WhatsApp message to: ${formattedTo}`)

    const explanation = (fullExplanation || aiMessage || '').toString().trim()
    const descriptionText = (description || 'No description provided').toString().trim()
    const titleText = (title || 'Security Alert').toString().trim()

    const messageParts = [
      `*[ALERT] ${titleText}*`,
      descriptionText,
      explanation ? `*AI Explanation:*\n${explanation}` : '',
      `Generated by Daredevil real-time monitoring.`
    ].filter(Boolean)

    const message = truncateText(messageParts.join('\n\n'))

    // Send WhatsApp message using Twilio
    const messageRequest: any = {
      body: message,
      from: formattedFrom,
      to: formattedTo
    }
    if (process.env.TWILIO_MESSAGING_SERVICE_SID) {
      messageRequest.messagingServiceSid = process.env.TWILIO_MESSAGING_SERVICE_SID
      delete messageRequest.from
    }
    const result = await client.messages.create(messageRequest)

    console.log('WhatsApp message sent successfully:', result.sid)
    return NextResponse.json({ data: { sid: result.sid } })
  } catch (error: any) {
    console.error('Unexpected error in WhatsApp API:', error)
    const twilioErrorMessage = error?.message || 'Unknown error'
    const twilioCode = error?.code || null
    const hint =
      twilioCode === 63007
        ? 'The FROM number is not WhatsApp-enabled on Twilio. Use Sandbox FROM (usually +14155238886) or a WhatsApp-approved sender.'
        : undefined
    return NextResponse.json({ error: twilioErrorMessage, code: twilioCode, hint }, { status: 500 })
  }
}
