// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/example-navbar" | "/forgot-password" | "/pages/mainOptions" | "/pages/nlp-query-interface" | "/pages/realtimeStreamPage" | "/pages/saved-videos" | "/pages/statistics" | "/pages/ufdr-3d-visualization" | "/pages/ufdr-3d-visualization-gnn" | "/pages/ufdr-3d-visualization-new" | "/pages/ufdr-analysis" | "/pages/upload" | "/pages/uploadOneVideoPage" | "/pages/video/[id]" | "/protected" | "/protected/reset-password" | "/sign-in" | "/sign-up" | "/test/email-test" | "/test/security-alert" | "/test/testEmail" | "/test/testJsonBoxesPage" | "/test/testJsonBoxesVideo" | "/test/whatsapp-setup" | "/test/whatsapp-test"
type AppRouteHandlerRoutes = "/api/analyze" | "/api/chat" | "/api/conversation" | "/api/get-twilio-config" | "/api/gnn-analysis" | "/api/key-status" | "/api/nlp-query" | "/api/send-email" | "/api/send-whatsapp" | "/api/summary" | "/api/ufdr-3d-visualization" | "/api/ufdr-ingest" | "/api/upload" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/analyze": {}
  "/api/chat": {}
  "/api/conversation": {}
  "/api/get-twilio-config": {}
  "/api/gnn-analysis": {}
  "/api/key-status": {}
  "/api/nlp-query": {}
  "/api/send-email": {}
  "/api/send-whatsapp": {}
  "/api/summary": {}
  "/api/ufdr-3d-visualization": {}
  "/api/ufdr-ingest": {}
  "/api/upload": {}
  "/auth/callback": {}
  "/example-navbar": {}
  "/forgot-password": {}
  "/pages/mainOptions": {}
  "/pages/nlp-query-interface": {}
  "/pages/realtimeStreamPage": {}
  "/pages/saved-videos": {}
  "/pages/statistics": {}
  "/pages/ufdr-3d-visualization": {}
  "/pages/ufdr-3d-visualization-gnn": {}
  "/pages/ufdr-3d-visualization-new": {}
  "/pages/ufdr-analysis": {}
  "/pages/upload": {}
  "/pages/uploadOneVideoPage": {}
  "/pages/video/[id]": { "id": string; }
  "/protected": {}
  "/protected/reset-password": {}
  "/sign-in": {}
  "/sign-up": {}
  "/test/email-test": {}
  "/test/security-alert": {}
  "/test/testEmail": {}
  "/test/testJsonBoxesPage": {}
  "/test/testJsonBoxesVideo": {}
  "/test/whatsapp-setup": {}
  "/test/whatsapp-test": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
