// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth-pages)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(auth-pages)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-pages)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/(auth-pages)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-pages)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/(auth-pages)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/example-navbar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/example-navbar">> = Specific
  const handler = {} as typeof import("../../app/example-navbar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/mainOptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/mainOptions">> = Specific
  const handler = {} as typeof import("../../app/pages/mainOptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/nlp-query-interface/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/nlp-query-interface">> = Specific
  const handler = {} as typeof import("../../app/pages/nlp-query-interface/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/realtimeStreamPage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/realtimeStreamPage">> = Specific
  const handler = {} as typeof import("../../app/pages/realtimeStreamPage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/saved-videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/saved-videos">> = Specific
  const handler = {} as typeof import("../../app/pages/saved-videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/statistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/statistics">> = Specific
  const handler = {} as typeof import("../../app/pages/statistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/ufdr-3d-visualization-gnn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/ufdr-3d-visualization-gnn">> = Specific
  const handler = {} as typeof import("../../app/pages/ufdr-3d-visualization-gnn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/ufdr-3d-visualization-new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/ufdr-3d-visualization-new">> = Specific
  const handler = {} as typeof import("../../app/pages/ufdr-3d-visualization-new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/ufdr-3d-visualization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/ufdr-3d-visualization">> = Specific
  const handler = {} as typeof import("../../app/pages/ufdr-3d-visualization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/ufdr-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/ufdr-analysis">> = Specific
  const handler = {} as typeof import("../../app/pages/ufdr-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/upload">> = Specific
  const handler = {} as typeof import("../../app/pages/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/uploadOneVideoPage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/uploadOneVideoPage">> = Specific
  const handler = {} as typeof import("../../app/pages/uploadOneVideoPage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/video/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/video/[id]">> = Specific
  const handler = {} as typeof import("../../app/pages/video/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/protected/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/protected">> = Specific
  const handler = {} as typeof import("../../app/protected/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/protected/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/protected/reset-password">> = Specific
  const handler = {} as typeof import("../../app/protected/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/email-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/email-test">> = Specific
  const handler = {} as typeof import("../../app/test/email-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/security-alert/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/security-alert">> = Specific
  const handler = {} as typeof import("../../app/test/security-alert/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/testEmail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/testEmail">> = Specific
  const handler = {} as typeof import("../../app/test/testEmail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/testJsonBoxesPage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/testJsonBoxesPage">> = Specific
  const handler = {} as typeof import("../../app/test/testJsonBoxesPage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/testJsonBoxesVideo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/testJsonBoxesVideo">> = Specific
  const handler = {} as typeof import("../../app/test/testJsonBoxesVideo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/whatsapp-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/whatsapp-setup">> = Specific
  const handler = {} as typeof import("../../app/test/whatsapp-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/whatsapp-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/whatsapp-test">> = Specific
  const handler = {} as typeof import("../../app/test/whatsapp-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze">> = Specific
  const handler = {} as typeof import("../../app/api/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversation">> = Specific
  const handler = {} as typeof import("../../app/api/conversation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/get-twilio-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/get-twilio-config">> = Specific
  const handler = {} as typeof import("../../app/api/get-twilio-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gnn-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gnn-analysis">> = Specific
  const handler = {} as typeof import("../../app/api/gnn-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/key-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/key-status">> = Specific
  const handler = {} as typeof import("../../app/api/key-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nlp-query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nlp-query">> = Specific
  const handler = {} as typeof import("../../app/api/nlp-query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/send-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-email">> = Specific
  const handler = {} as typeof import("../../app/api/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/send-whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-whatsapp">> = Specific
  const handler = {} as typeof import("../../app/api/send-whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/summary">> = Specific
  const handler = {} as typeof import("../../app/api/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ufdr-3d-visualization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ufdr-3d-visualization">> = Specific
  const handler = {} as typeof import("../../app/api/ufdr-3d-visualization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ufdr-ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ufdr-ingest">> = Specific
  const handler = {} as typeof import("../../app/api/ufdr-ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(auth-pages)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth-pages)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
